ALTER TABLE flights
  ADD COLUMN IF NOT EXISTS origin VARCHAR(128) NOT NULL DEFAULT '';

ALTER TABLE flights
  ADD COLUMN IF NOT EXISTS destination VARCHAR(128) NOT NULL DEFAULT '';

ALTER TABLE flights
  ADD COLUMN IF NOT EXISTS departure_time TIMESTAMPTZ NULL;

ALTER TABLE flights
  ADD COLUMN IF NOT EXISTS arrival_time TIMESTAMPTZ NULL;

